### ISSUE TITLE
Please add an Example for Treeview Widget with Json Data

### ISSUE THREAD

**Issue by kprathap23** [lohanidamodar/flutter_ui_challenges#14]

**Comment by cimplesid** [comment]
@kprathap23  can you provide more info about how the json look like  ?

**Comment by kprathap23** [comment]
please see this sample json 
https://github.com/kprathap23/FlutterApps/blob/master/data.json

**Comment by cimplesid** [comment]
If u also have the sample ui it would be great

**Comment by kprathap23** [comment]
![Screenshot_2019-09-12-12-19-33-400_](https://user-images.githubusercontent.com/2254065/64760588-b8c06b80-d557-11e9-9b9e-30362cf544a6.png)

**Comment by kprathap23** [comment]
found solution
