### ISSUE TITLE
compiler error 

### ISSUE THREAD

**Issue by amjadalfawal** [lohanidamodar/flutter_ui_challenges#21]
****
Compiler message:
/D:/fullter/.pub-cache/git/Flare-Flutter-6606b73bf4f7b87105a6febfbb5f2167cf8b8977/flare_flutter/lib/flare.dart:580:14: Error: The method 'FlutterActor.makeShapeNode' has fewer positional arguments than those of overridden method 'Actor.makeShapeNode'.
  ActorShape makeShapeNode() {
             ^
/D:/fullter/.pub-cache/git/Flare-Flutter-e3d2414dfbd25e632510dad6959a1c18c2d585f8/flare_dart/lib/actor.dart:68:14: Context: This is the overridden method ('makeShapeNode').
  ActorShape makeShapeNode(ActorShape source) {
             ^
Compiler failed on D:\flutter\flutter_ui_challenges\lib\main.dart

FAILURE: Build failed with an exception.

* Where:
Script 'D:\fullter\packages\flutter_tools\gradle\flutter.gradle' line: 765

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebugX86'.
> Process 'command 'D:\fullter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        11.7s
Gradle task assembleDebug failed with exit code 1

**Comment by lohanidamodar** [comment]
@amjadalfawal This is because of old Flutter Flare dependency. Which is already fixed in our repository. Pull the latest code from repository (check pubspec.yaml for flare_flutter: 1.5.9), and if the issue still exists do `flutter clean` before building. 
If the problem still exists do reopen the issue.
