### ISSUE TITLE
i need litle help

### ISSUE THREAD

**Issue by amjadalfawal** [lohanidamodar/flutter_ui_challenges#22]
![image](https://user-images.githubusercontent.com/37481122/66525086-000d2e00-eafd-11e9-9654-49e216dfa3b5.png)
I'm trying to build rtl version. how to mirror this clipper any helps? 
oval-right-clipper i need oval-left-clipper
  @override
  Path getClip(Size size) {
    var path = Path();

    path.lineTo(0, 0);
    path.lineTo(size.width - 40, 0);
    path.quadraticBezierTo(
        size.width, size.height / 4, size.width, size.height / 2);
    path.quadraticBezierTo(size.width, size.height - (size.height / 4),
        size.width - 40, size.height);
    path.lineTo(0, size.height);
    return path;
  }

**Comment by lohanidamodar** [comment]
Here, use this...
```
@override
  Path getClip(Size size) {
    var path = Path();
    path.lineTo(0, 0);
    path.lineTo(40, 0);
    path.quadraticBezierTo(
        0, size.height / 4, 0, size.height/2);
    path.quadraticBezierTo(
        0, size.height - (size.height / 4), 40, size.height);
    path.lineTo(size.width, size.height);
    path.lineTo(size.width, 0);
    return path;
  }
```
