### ISSUE TITLE
MediaQuery.of() called with a context that does not contain a MediaQuery. IN SPRINGYSLIDER

### ISSUE THREAD

**Issue by suryac1508** [lohanidamodar/flutter_ui_challenges#23]
The following assertion was thrown building SpringySliderPage:
I/flutter ( 2382): MediaQuery.of() called with a context that does not contain a MediaQuery.
I/flutter ( 2382): No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of().
I/flutter ( 2382): This can happen because you do not have a WidgetsApp or MaterialApp widget (those widgets introduce
I/flutter ( 2382): a MediaQuery), or it can happen if the context you use comes from a widget above those widgets.
I/flutter ( 2382): The context used was:
I/flutter ( 2382):   Scaffold(dirty, state: ScaffoldState#ee670(lifecycle state: initialized, tickers: tracking 2
I/flutter ( 2382): tickers))

**Comment by lohanidamodar** [comment]
Need to see the code your are copying that into. Haven't got any more interaction on this so closing this issue. If you still have the problem please reach out with minimum run able code to reproduce error.
