### ISSUE TITLE
UI request

### ISSUE THREAD

**Issue by ansh466** [lohanidamodar/flutter_ui_challenges#24]
![IMG-20191023-WA0003](https://user-images.githubusercontent.com/56970040/67499454-c01e7d00-f69e-11e9-875c-876f14d50eeb.jpg)
Please design image pop-up with auto adjustable size depends on image with over laye share and close button

**Comment by ansh466** [comment]
Please help me.

**Comment by lohanidamodar** [comment]
@ansh466 Please checkout this latest added UI, this might solve your request.
https://github.com/lohanidamodar/flutter_ui_challenges/blob/develop/lib/src/pages/misc/image_popup.dart
