### ISSUE TITLE
Ui issue

### ISSUE THREAD

**Issue by ansh466** [lohanidamodar/flutter_ui_challenges#25]
![Screenshot_2019-10-24-21-00-32-21_6ac61b758441ef2add948e8a70324add](https://user-images.githubusercontent.com/56970040/67501194-7e430600-f6a1-11e9-9e41-3ba30730993d.png)
In this UI I have an issue.. gap between keyboard and textbox .. please resolve.thanks In advance.

**Comment by lohanidamodar** [comment]
@ansh466 please check this ui similar to your request, may be the code there will help you figure out what's different in your design
https://github.com/lohanidamodar/flutter_ui_challenges/blob/master/lib/src/pages/misc/chat2.dart

Here is the output of the UI,
https://github.com/lohanidamodar/flutter_ui_challenges/blob/master/screenshots/chat2.png

**Comment by ansh466** [comment]
Actually my chat screen is open in under the bottom navigation bar and that is the reason I got gap between typing box and keyboard.
