### ISSUE TITLE
ios xcode build failed？

### ISSUE THREAD

**Issue by toosui** [lohanidamodar/flutter_ui_challenges#31]
how to run this flutter_ui_challenges succese？？
failed tip：googlexxxxx.plist
求助 大佬

**Comment by lohanidamodar** [comment]
@toosui we have implemented firebase in our project so in order to run you need to create your own firebase project from console.firebase.google.com and add your google****.plist file into your project.

**Comment by toosui** [comment]
so i need to download my googlexxxx.plist from &nbsp;console.firebase.google.com&nbsp;and add this in my project？



发自我的iPhone


------------------ Original ------------------

**Comment by lohanidamodar** [comment]
Yes exactly!

**Comment by lohanidamodar** [comment]
Not  getting any more interaction. Hope this issue is fixed. If there is any more problem, you can reach out any time.

**Comment by toosui** [comment]
can i add your wechat or other... to exchange ！i hope learn more things from this project and learn from you ！i think you flutter is very 牛逼



发自我的iPhone


------------------ Original ------------------

**Comment by lohanidamodar** [comment]
@toosui send me a email on dlohani48@gmail.com, I will send you other contact details on email if required.
