### ISSUE TITLE
com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 24 path $

### ISSUE THREAD

**Issue by wangyuetingtao** [lohanidamodar/flutter_ui_challenges#33]
flutter version：1.12.17
i met this problems：
Execution failed for task ':app:processDebugGoogleServices'.
> com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 24 path $

**Comment by lohanidamodar** [comment]
Is this the complete log?
Have you provided your own google-services.json?
Please, we need more details to troubleshoot.
