### ISSUE TITLE
Flutter SDK v1.12.13+hotfix.5

### ISSUE THREAD

**Issue by blondie63** [lohanidamodar/flutter_ui_challenges#36]
Hi i've tried to run firebase and branch without firebase with last sdk but there are many issues and app don't start..
Someone have tried ?

**Comment by lohanidamodar** [comment]
Hi, if the problem is regarding cached network image, you have to update the version to 2.0.0-rc. Should solve your problem. If you have any other problems, feel free to reopen the issue.
