### ISSUE TITLE
Android testing

### ISSUE THREAD

**Issue by blondie63** [lohanidamodar/flutter_ui_challenges#38]
Hi, i've tried to run on Android emulator api 29 after copied google-services.json in /android/app folder but i've this error:

Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software
rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Build file '/Users/mauro/Documents/_projects/Flutter/_Samples/flutter_ui_challenges/android/app/build.gradle' line: 53
                                                                        
* What went wrong:                                                      
A problem occurred evaluating project ':app'.                           
> path may not be null or empty string. path='null'                     
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 9s                                                      
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        14,6s
Gradle task assembleDebug failed with exit code 1

**Comment by lohanidamodar** [comment]
This issue is due to signing config please refer to this [issue](https://github.com/lohanidamodar/flutter_ui_challenges/issues/2)
