### ISSUE TITLE
iOS testing

### ISSUE THREAD

**Issue by blondie63** [lohanidamodar/flutter_ui_challenges#39]
Hi, i've tried to run on iOS emulator after copied google-services.json in /android/app folder but i've this error:
Launching lib/main.dart on iPad Pro (11-inch) in debug mode...
Running pod install...                                             13,0s
Running Xcode build...                                                  
                                                   
 ├─Assembling Flutter resources...                          13,2s
 └─Compiling, linking and signing...                         3,7s
Xcode build done.                                           114,6s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    /Users/mauro/Documents/_projects/Flutter/_Samples/flutter_ui_challenges/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:101:9:
    warning: 'dispatch_queue_set_specific' is only available on iOS 5.0 or newer [-Wunguarded-availability]
            dispatch_queue_set_specific(_queue, kDispatchQueueSpecificKey, (__bridge void *)self, NULL);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'Foundation' imported from
    /Users/mauro/Documents/_projects/Flutter/_Samples/flutter_ui_challenges/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.h:9:
    In module 'CoreFoundation' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System
    /Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
    In module 'Dispatch' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System
    /Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/usr/in
    clude/dispatch/queue.h:1498:1: note: 'dispatch_queue_set_specific' has been marked as being introduced in iOS 5.0 here, but
    the deployment target is iOS 4.3.0
    dispatch_queue_set_specific(dispatch_queue_t queue, const void *key,
    ^
    /Users/mauro/Documents/_projects/Flutter/_Samples/flutter_ui_challenges/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:101:9:
    note: enclose 'dispatch_queue_set_specific' in an @available check to silence this warning
            dispatch_queue_set_specific(_queue, kDispatchQueueSpecificKey, (__bridge void *)self, NULL);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/mauro/Documents/_projects/Flutter/_Samples/flutter_ui_challenges/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:184:54:
    warning: 'dispatch_get_specific' is only available on iOS 5.0 or newer [-Wunguarded-availability]
        FMDatabaseQueue *currentSyncQueue = (__bridge id)dispatch_get_specific(kDispatchQueueSpecificKey);
                                                         ^~~~~~~~~~~~~~~~~~~~~
    In module 'Foundation' imported from
    /Users/mauro/Documents/_projects/Flutter/_Samples/flutter_ui_challenges/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.h:9:
    In module 'CoreFoundation' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System
    /Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
    In module 'Dispatch' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System
    /Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/usr/in
    clude/dispatch/queue.h:1554:1: note: 'dispatch_get_specific' has been marked as being introduced in iOS 5.0 here, but the
    deployment target is iOS 4.3.0
    dispatch_get_specific(const void *key);
    ^
    /Users/mauro/Documents/_projects/Flutter/_Samples/flutter_ui_challenges/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:184:54:
    note: enclose 'dispatch_get_specific' in an @available check to silence this warning
        FMDatabaseQueue *currentSyncQueue = (__bridge id)dispatch_get_specific(kDispatchQueueSpecificKey);
                                                         ^~~~~~~~~~~~~~~~~~~~~
    2 warnings generated.
    /Users/mauro/Documents/_projects/Flutter/_Samples/flutter_ui_challenges/ios/Pods/FMDB/src/fmdb/FMDatabase.m:1486:15:
    warning: 'sqlite3_wal_checkpoint_v2' is only available on iOS 5.0 or newer [-Wunguarded-availability]
        int err = sqlite3_wal_checkpoint_v2(_db, dbName, checkpointMode, logFrameCount, checkpointCount);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'SQLite3' imported from
    /Users/mauro/Documents/_projects/Flutter/_Samples/flutter_ui_challenges/ios/Pods/FMDB/src/fmdb/FMDatabase.m:8:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/usr/in
    clude/sqlite3.h:8428:16: note: 'sqlite3_wal_checkpoint_v2' has been marked as being introduced in iOS 5.0 here, but the
    deployment target is iOS 4.3.0
    SQLITE_API int sqlite3_wal_checkpoint_v2(
                   ^
    /Users/mauro/Documents/_projects/Flutter/_Samples/flutter_ui_challenges/ios/Pods/FMDB/src/fmdb/FMDatabase.m:1486:15: note:
    enclose 'sqlite3_wal_checkpoint_v2' in an @available check to silence this warning
        int err = sqlite3_wal_checkpoint_v2(_db, dbName, checkpointMode, logFrameCount, checkpointCount);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~
    1 warning generated.
    /Users/mauro/Documents/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in-4.1.1/ios/Classes/FLTGoogleSignInPlugi
    n.m:138:13: warning: unused variable 'sourceApplication' [-Wunused-variable]
      NSString *sourceApplication = options[UIApplicationOpenURLOptionsSourceApplicationKey];
                ^
    /Users/mauro/Documents/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in-4.1.1/ios/Classes/FLTGoogleSignInPlugi
    n.m:138:41: warning: 'UIApplicationOpenURLOptionsSourceApplicationKey' is only available on iOS 9.0 or newer
    [-Wunguarded-availability]
      NSString *sourceApplication = options[UIApplicationOpenURLOptionsSourceApplicationKey];
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'UIKit' imported from /Users/mauro/Documents/_projects/Flutter/_Samples/flutter_ui_challenges/ios/Pods/Target
    Support Files/google_sign_in/google_sign_in-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System
    /Library/Frameworks/UIKit.framework/Headers/UIApplication.h:518:51: note: 'UIApplicationOpenURLOptionsSourceApplicationKey'
    has been marked as being introduced in iOS 9.0 here, but the deployment target is iOS 8.0.0
    UIKIT_EXTERN UIApplicationOpenURLOptionsKey const UIApplicationOpenURLOptionsSourceApplicationKey
    NS_SWIFT_NAME(sourceApplication) API_AVAILABLE(ios(9.0));   // value is an NSString containing the bundle ID of the
    originating application; non-nil if the originating application and this application share the same team identifier
                                                      ^
    /Users/mauro/Documents/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in-4.1.1/ios/Classes/FLTGoogleSignInPlugi
    n.m:138:41: note: enclose 'UIApplicationOpenURLOptionsSourceApplicationKey' in an @available check to silence this warning
      NSString *sourceApplication = options[UIApplicationOpenURLOptionsSourceApplicationKey];
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    2 warnings generated.
    /Users/mauro/Documents/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_remote_config-0.3.0+1/ios/Classes/FirebaseRe
    moteConfigPlugin.m:52:65: warning: 'isDeveloperModeEnabled' is deprecated: This no longer needs to be set during
    development. Refer to documentation for additional details. [-Wdeprecated-declarations]
            [[NSNumber alloc] initWithBool:[firRemoteConfigSettings isDeveloperModeEnabled]];
                                                                    ^
    In file included from
    /Users/mauro/Documents/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_remote_config-0.3.0+1/ios/Classes/FirebaseRe
    moteConfigPlugin.m:8:
    In file included from
    /Users/mauro/Documents/_projects/Flutter/_Samples/flutter_ui_challenges/ios/Pods/Headers/Private/Firebase/Firebase.h:142:
    In file included from
    /Users/mauro/Documents/_projects/Flutter/_Samples/flutter_ui_challenges/ios/Pods/Headers/Private/FirebaseRemoteConfig/Fireb
    aseRemoteConfig.h:17:
    /Users/mauro/Documents/_projects/Flutter/_Samples/flutter_ui_challenges/ios/Pods/Headers/Private/FirebaseRemoteConfig/FIRRe
    moteConfig.h:141:37: note: property 'isDeveloperModeEnabled' is declared deprecated here
    @property(nonatomic, readonly) BOOL isDeveloperModeEnabled DEPRECATED_MSG_ATTRIBUTE(
                                        ^
    /Users/mauro/Documents/_projects/Flutter/_Samples/flutter_ui_challenges/ios/Pods/Headers/Private/FirebaseRemoteConfig/FIRRe
    moteConfig.h:141:60: note: 'isDeveloperModeEnabled' has been explicitly marked deprecated here
    @property(nonatomic, readonly) BOOL isDeveloperModeEnabled DEPRECATED_MSG_ATTRIBUTE(
                                                               ^
    In module 'Darwin' imported from
    /Users/mauro/Documents/_projects/Flutter/_Samples/flutter_ui_challenges/ios/Pods/Headers/Private/FirebaseAuth/FIRAuth.h:17:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/usr/in
    clude/AvailabilityMacros.h:182:64: note: expanded from macro 'DEPRECATED_MSG_ATTRIBUTE'
                #define DEPRECATED_MSG_ATTRIBUTE(s) __attribute__((deprecated(s)))
                                                                   ^
    /Users/mauro/Documents/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_remote_config-0.3.0+1/ios/Classes/FirebaseRe
    moteConfigPlugin.m:61:42: warning: 'initWithDeveloperModeEnabled:' is deprecated: This no longer needs to be set during
    development. Refer to documentation for additional details. [-Wdeprecated-declarations]
            [[FIRRemoteConfigSettings alloc] initWithDeveloperModeEnabled:debugMode];
                                             ^
    In file included from
    /Users/mauro/Documents/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_remote_config-0.3.0+1/ios/Classes/FirebaseRe
    moteConfigPlugin.m:8:
    In file included from
    /Users/mauro/Documents/_projects/Flutter/_Samples/flutter_ui_challenges/ios/Pods/Headers/Private/Firebase/Firebase.h:142:
    In file included from
    /Users/mauro/Documents/_projects/Flutter/_Samples/flutter_ui_challenges/ios/Pods/Headers/Private/FirebaseRemoteConfig/Fireb
    aseRemoteConfig.h:17:
    /Users/mauro/Documents/_projects/Flutter/_Samples/flutter_ui_challenges/ios/Pods/Headers/Private/FirebaseRemoteConfig/FIRRe
    moteConfig.h:148:5: note: 'initWithDeveloperModeEnabled:' has been explicitly marked deprecated here
        DEPRECATED_MSG_ATTRIBUTE("This no longer needs to be set during development. Refer to "
        ^
    In module 'Darwin' imported from
    /Users/mauro/Documents/_projects/Flutter/_Samples/flutter_ui_challenges/ios/Pods/Headers/Private/FirebaseAuth/FIRAuth.h:17:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/usr/in
    clude/AvailabilityMacros.h:182:64: note: expanded from macro 'DEPRECATED_MSG_ATTRIBUTE'
                #define DEPRECATED_MSG_ATTRIBUTE(s) __attribute__((deprecated(s)))
                                                                   ^
    /Users/mauro/Documents/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_remote_config-0.3.0+1/ios/Classes/FirebaseRe
    moteConfigPlugin.m:108:54: warning: 'activateFetched' is deprecated: Use -[FIRRemoteConfig activate] instead.
    [-Wdeprecated-declarations]
        BOOL newConfig = [[FIRRemoteConfig remoteConfig] activateFetched];
                                                         ^
    In file included from
    /Users/mauro/Documents/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_remote_config-0.3.0+1/ios/Classes/FirebaseRe
    moteConfigPlugin.m:8:
    In file included from
    /Users/mauro/Documents/_projects/Flutter/_Samples/flutter_ui_challenges/ios/Pods/Headers/Private/Firebase/Firebase.h:142:
    In file included from
    /Users/mauro/Documents/_projects/Flutter/_Samples/flutter_ui_challenges/ios/Pods/Headers/Private/FirebaseRemoteConfig/Fireb
    aseRemoteConfig.h:17:
    /Users/mauro/Documents/_projects/Flutter/_Samples/flutter_ui_challenges/ios/Pods/Headers/Private/FirebaseRemoteConfig/FIRRe
    moteConfig.h:245:25: note: 'activateFetched' has been explicitly marked deprecated here
    - (BOOL)activateFetched DEPRECATED_MSG_ATTRIBUTE("Use -[FIRRemoteConfig activate] "
                            ^
    In module 'Darwin' imported from
    /Users/mauro/Documents/_projects/Flutter/_Samples/flutter_ui_challenges/ios/Pods/Headers/Private/FirebaseAuth/FIRAuth.h:17:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/usr/in
    clude/AvailabilityMacros.h:182:64: note: expanded from macro 'DEPRECATED_MSG_ATTRIBUTE'
                #define DEPRECATED_MSG_ATTRIBUTE(s) __attribute__((deprecated(s)))
                                                                   ^
    /Users/mauro/Documents/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_remote_config-0.3.0+1/ios/Classes/FirebaseRe
    moteConfigPlugin.m:139:40: warning: 'allKeysFromSource:namespace:' is deprecated: Use -[FIRRemoteConfig allKeysFromSource:]
    instead. [-Wdeprecated-declarations]
      NSArray *defaultKeys = [remoteConfig allKeysFromSource:FIRRemoteConfigSourceDefault
                                           ^
    In file included from
    /Users/mauro/Documents/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_remote_config-0.3.0+1/ios/Classes/FirebaseRe
    moteConfigPlugin.m:8:
    In file included from
    /Users/mauro/Documents/_projects/Flutter/_Samples/flutter_ui_challenges/ios/Pods/Headers/Private/Firebase/Firebase.h:142:
    In file included from
    /Users/mauro/Documents/_projects/Flutter/_Samples/flutter_ui_challenges/ios/Pods/Headers/Private/FirebaseRemoteConfig/Fireb
    aseRemoteConfig.h:17:
    /Users/mauro/Documents/_projects/Flutter/_Samples/flutter_ui_challenges/ios/Pods/Headers/Private/FirebaseRemoteConfig/FIRRe
    moteConfig.h:300:5: note: 'allKeysFromSource:namespace:' has been explicitly marked deprecated here
        DEPRECATED_MSG_ATTRIBUTE("Use -[FIRRemoteConfig allKeysFromSource:] instead.");
        ^
    In module 'Darwin' imported from
    /Users/mauro/Documents/_projects/Flutter/_Samples/flutter_ui_challenges/ios/Pods/Headers/Private/FirebaseAuth/FIRAuth.h:17:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/usr/in
    clude/AvailabilityMacros.h:182:64: note: expanded from macro 'DEPRECATED_MSG_ATTRIBUTE'
                #define DEPRECATED_MSG_ATTRIBUTE(s) __attribute__((deprecated(s)))
                                                                   ^
    4 warnings generated.
    error: Build input file cannot be found:
    '/Users/mauro/Documents/_projects/Flutter/_Samples/flutter_ui_challenges/ios/Runner/GoogleService-Info.plist' (in target
    'Runner' from project 'Runner')
    note: Using new build system
    note: Planning build
    note: Constructing build description
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 4.3, but the range of supported
    deployment target versions is 8.0 to 13.2.99. (in target 'FMDB' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported
    deployment target versions is 8.0 to 13.2.99. (in target 'gRPC-C++-gRPCCertificates-Cpp' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 4.3, but the range of supported
    deployment target versions is 8.0 to 13.2.99. (in target 'nanopb' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported
    deployment target versions is 8.0 to 13.2.99. (in target 'Protobuf' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported
    deployment target versions is 8.0 to 13.2.99. (in target 'GTMSessionFetcher' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported
    deployment target versions is 8.0 to 13.2.99. (in target 'BoringSSL-GRPC' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported
    deployment target versions is 8.0 to 13.2.99. (in target 'AppAuth' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 5.0, but the range of supported
    deployment target versions is 8.0 to 13.2.99. (in target 'leveldb-library' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported
    deployment target versions is 8.0 to 13.2.99. (in target 'abseil' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported
    deployment target versions is 8.0 to 13.2.99. (in target 'gRPC-Core' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported
    deployment target versions is 8.0 to 13.2.99. (in target 'GTMAppAuth' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported
    deployment target versions is 8.0 to 13.2.99. (in target 'gRPC-C++' from project 'Pods')

Could not build the application for the simulator.
Error launching application on iPad Pro (11-inch).

Some help?

**Comment by blondie63** [comment]
I managed to get it started by adding the plist file and modifying the pod file

**Comment by blondie63** [comment]
App start but there are many errors.. :(
<img width="608" alt="flutter-ui-challeng ko" src="https://user-images.githubusercontent.com/1261851/72092183-13a17e00-3312-11ea-96c9-0070d90fd808.png">

**Comment by blondie63** [comment]
I've seen a strange thing running "flutter run" to ios
a build folder will be create but with some errors, look:
<img width="860" alt="flutter-ui-challeng build ko" src="https://user-images.githubusercontent.com/1261851/72158388-65054800-33ba-11ea-8158-68fcaba10887.png">
do you know why?

**Comment by lohanidamodar** [comment]
Try flutter clean and flutter packages get once again. Haven't had the issue, all code are correct and building.

**Comment by blondie63** [comment]
I hope to don't wast your time but i've tried to exclude some folders.. look:
<img width="1285" alt="ui-chall-errs" src="https://user-images.githubusercontent.com/1261851/72221293-7f295c80-3559-11ea-877b-8a248abbbe40.png">
anyway app start with err same -> https://github.com/lohanidamodar/flutter_ui_challenges/issues/39#issuecomment-572679426

do you have a guide to setup info.plist ?
i've followed this: https://github.com/flutter/flutter/issues/34437#issuecomment-502325212 but it does'nt works..

**Comment by lohanidamodar** [comment]
In excluded folders just add `build` instead of `**/build/**`

**Comment by lohanidamodar** [comment]
That is the correct way to add info.plist config, however did you replace this `<string>com.googleusercontent.apps.861823949799-vc35cprkp249096uujjn0vvnmcvjppkn</string>` with your CLIENT_REVERSED_ID from your GoogleService-Info.plist ?
