### ISSUE TITLE
Laggy when open Animation on iOS devices

### ISSUE THREAD

**Issue by hp1909** [lohanidamodar/flutter_ui_challenges#4]
I run the project on iOS devices, it does not work smoothly. Please check it.

**Comment by lohanidamodar** [comment]
@hp1909 please specify which UIs you are talking about.
Also, the designs may not always be optimized, some are old designs of when I just began learning flutter, so bear with me.

If you have any specific UI that is not smooth, let me know, I will try to optimize.

Thank you.

**Comment by cimplesid** [comment]
> I run the project on iOS devices, it does not work smoothly. Please check it.

make sure its not your simulator making any trouble

**Comment by hp1909** [comment]
It happens like this problem:
https://github.com/flutter/flutter/issues/20845

**Comment by lohanidamodar** [comment]
@hp1909 Yes, I see the problem, hope there will be a fix soon!

**Comment by hp1909** [comment]
> @hp1909 Yes, I see the problem, hope there will be a fix soon!

The solution is you have to wrap your Text on an SizedBox.

**Comment by lohanidamodar** [comment]
Not an optimal solution but for now works by wrapping by sizedbox. Thanks for the tip @hp1909

**Comment by hp1909** [comment]
I found another solution works stably that you use FittedBox. Therefore you don't need to declare width and height like SizedBox
