### ISSUE TITLE
Animation page doesn't have back button

### ISSUE THREAD

**Issue by PauliusLeonardas** [lohanidamodar/flutter_ui_challenges#41]
(iOS)
Hi,

in app, when you choose 'Animations (5 layouts)' > 'Fancy Appbar Animation' it does not contains the back button to UI Challenges view and now user is stuck in the animation window.

It's probably this anim idk [link](https://github.com/lohanidamodar/flutter_ui_challenges/blob/master/lib/src/pages/animations/anim3.dart)

(Note: 'Hero Animation' has it's back button slightly higher and it might goes under the top bar and sometimes it's hard to press it)

Update:
Had more time and found that these contains no back arrow as well:

- Profile Two
- Profile Four
- Authentication all (except Signup One)
- Settings Two
- List Two
- Invitation all (last one has but not works
- and others probably going bellow..

**Comment by lohanidamodar** [comment]
Hi, those are sample UIs trying to replicate from other real world scenarios that is why some UIs don't have the back button as their real sample don't have as some of them are intro screen or main screens of app. 

If you are stuck, In iOS you can go back just by swiping right from the left edge of the screen and in android you can use hardware back button. You don't have to be stuck.

**Comment by PauliusLeonardas** [comment]
I understand, but my point is that if you go to view a result, let's say animation, you can't go back to view where code buttons are.

On Iphone, yes you can swipe from left to right, but then you need close app.

It's just that it would be nice (perhaps) to have a back button for integrity and save time basically.

**Comment by lohanidamodar** [comment]
> On Iphone, yes you can swipe from left to right, but then you need close app.
You do not need to close app, if you swipe from left edge of screen to right  on iphone, its basically like the hardware back button on android, you can go back. But will add back buttons if that's more comfortable. Thank you.
