### ISSUE TITLE
Bottom Sheet UI Request?

### ISSUE THREAD

**Issue by NicoAnPra** [lohanidamodar/flutter_ui_challenges#43]
Hi Sir, can we request a feature? If yes, please help me to make full screen bottom sheet like google maps bottom sheet on android os devices.

I really don't know how to make it, when we drag the bottom sheet onto the appbar it become full screen, it become one with the appbar / with the whole page screen and scrollable, and when we click on some place the bottom sheet even has its own appbar with the selected place/location as an appbar name.

Please consider for make this type of bottom sheet sir.

thanks sir, sorry for my bad english.

**Comment by lohanidamodar** [comment]
I think the UI you are looking for will be solved by this package.
https://pub.dev/packages/sliding_up_panel
If not, please let us know with screenshot or screen record of what you want, we will try to include that in our future updates.
Thank you

**Comment by NicoAnPra** [comment]
Thanks, yup, its something like that, but I don't know if I can do it with that widget or not, here what I need to learn right now:
1. About fullscreen bottom sheet with custom appbar
- In SS bellow, in first image its just normal bottom sheet, then
- in second image its become fullscreen page (maybe?), and then
- in third image, when we scroll down its has its own appbar with "Pulau Ubin" as a title.
![Screenshot_2020-02-01_211343 - Copy - Copy](https://user-images.githubusercontent.com/57020051/73593709-8d0b4580-4539-11ea-8639-1613cb899121.jpg)

2. About fullscreen bottom sheet that combined with appbar
- In first and second images just a normal bottom sheet, but the different is in third image
- In third image, the bottom sheet become one with appbar (main search appbar)
- in fourth images we can see the shadow of the search appbar.
![Screenshot_2020-02-01_210954 - Copy - Copy](https://user-images.githubusercontent.com/57020051/73593747-05720680-453a-11ea-851d-32cefd6189c3.jpg)

Please consider to make this type of bottom sheet on your app, your app is really helpful,  we can see preview for the widget alongside with its code, it is really useful for learning using your app.

**Comment by lohanidamodar** [comment]
HI, sorry we have not implemented your request, but I have found a plugin that supports your need please check out their example. Thank you
https://github.com/BendixMa/sliding-sheet
