### ISSUE TITLE
UI CHALLENGE PACKAGE

### ISSUE THREAD

**Issue by MichalGazdik** [lohanidamodar/flutter_ui_challenges#45]
Hello, how can I install flutter UI challenges package into my app? Cannot find it anywhere on the internet :-( thanks

**Comment by lohanidamodar** [comment]
I am sorry it's not a package, its a collection of various ui designs, if you like any component, you can copy the code and/or customize and use it in your application.
There is no package. These are the Sample UIs implemented in flutter.
