### ISSUE TITLE
UI challenges package

### ISSUE THREAD

**Issue by MichalGazdik** [lohanidamodar/flutter_ui_challenges#46]
Hello where can I download flutter_ui_challenges package? Cannot find it anywhere. Thank you

**Comment by lohanidamodar** [comment]
Hi, did you not check my reply to your previous issue?
https://github.com/lohanidamodar/flutter_ui_challenges/issues/45

**Comment by MichalGazdik** [comment]
Hi probably missed it. Didn’t get any notification.

Regards,
Michal
