### ISSUE TITLE
Remove firebase, google_sign_in and so on?

### ISSUE THREAD

**Issue by liudonghua123** [lohanidamodar/flutter_ui_challenges#48]
Can we remove firebase, google_sign_in and other authentication to provide pure flutter ui demonstration. In this way, we can make it more easier to run it locally and make it available for flutter web and desktop(MacOS, Linux, Windows) support.

I like the examples in this repo, it help me to learn flutter better. But now I have to modified some staffs to make it build locally for android. There are a lot of issues about firebase, google_sign_in and some releated key, secret integration when it comes to web and desktop support. I hope we can create  a branch for removing firebase, google_sign_in and so on, provide pure ui challenges and support web and desktop. A lot of dependences are dart package, not flutter plugin, so I think it maybe easy to run it on web and desktop.

Hope this repo become better, popular and more easier for flutter beginners. Thanks for the wonderful project. It really help me a lot.

**Comment by lohanidamodar** [comment]
Sure I like the Idea, I too have previously created the branch [without-firebase](https://github.com/lohanidamodar/flutter_ui_challenges/tree/without-firebase) for the same purpose. But I haven't been able to update the branch with the latest UI samples added after updating with firebase and google sign in.

**Comment by liudonghua123** [comment]
I would like try to remove the authentication related code like `firebase` , `google_sign_in`, and send a pr to the existed old `without-firebase` branch. And maybe remove some dependences to make it work on web and desktop.

**Comment by lohanidamodar** [comment]
That's great. And I really appreciate your enthusiasm and support.

**Comment by liudonghua123** [comment]
Hi, I modified the code, removed some dependences and make it work for mobile, web and desktop. See more details on https://github.com/lohanidamodar/flutter_ui_challenges/pull/49.

**Comment by lohanidamodar** [comment]
@liudonghua123 Thank you for your suggestion and help. I have updated the repo to work on web and desktop.
