### ISSUE TITLE
Error during compilation

### ISSUE THREAD

**Issue by melying** [lohanidamodar/flutter_ui_challenges#53]
Hi, 

after I have fetched the dependencies and tried to run the app in the simulator, I get the following error message: 

`Compiler message:
lib/src/pages/profile/profile9.dart:59:22: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../Desktop/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
                    .headline6
                     ^^^^^^^^^
lib/src/pages/profile/profile9.dart:91:66: Error: The getter 'headline4' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../Desktop/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline4'.
                              style: Theme.of(context).textTheme.headline4,
                                                                 ^^^^^^^^^
lib/src/pages/profile/profile9.dart:96:66: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../Desktop/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
                              style: Theme.of(context).textTheme.subtitle1,
                                                                 ^^^^^^^^^
lib/src/pages/profile/profile9.dart:106:66: Error: The getter 'headline4' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../Desktop/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline4'.
                              style: Theme.of(context).textTheme.headline4,
                                                                 ^^^^^^^^^
lib/src/pages/profile/profile9.dart:111:66: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../Desktop/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
                              style: Theme.of(context).textTheme.subtitle1,
                                                                 ^^^^^^^^^
lib/src/pages/profile/profile9.dart:123:52: Error: The getter 'headline5' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../Desktop/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline5'.
                style: Theme.of(context).textTheme.headline5,
                                                   ^^^^^^^^^
lib/src/pages/profile/profile9.dart:143:52: Error: The getter 'headline5' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../Desktop/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline5'.
                style: Theme.of(context).textTheme.headline5,
                                                   ^^^^^^^^^
lib/src/pages/profile/profile9.dart:219:13: Error: No named parameter with the name 'clipBehavior'.
            clipBehavior: Clip.antiAlias,
            ^^^^^^^^^^^^
../../Desktop/flutter/packages/flutter/lib/src/widgets/container.dart:302:3: Context: Found this candidate, but the arguments don't match.
  Container({
  ^^^^^^^^^
lib/src/pages/profile/profile9.dart:242:20: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../Desktop/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
                  .headline6
                   ^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
Failed to build bundle.
Error launching application on iPhone 11.`

Please help with this, thanks!

**Comment by lohanidamodar** [comment]
You must use the latest version of Flutter (post output of your `flutter doctor -v`)

**Comment by melying** [comment]
This was the output:

**Comment by lohanidamodar** [comment]
Upgrade your flutter (1.17)

**Comment by melying** [comment]
Ok thanks, appreciate your replies!!

**Comment by lohanidamodar** [comment]
No problem. do reopen the issue if you still have problem after upgrades.
