### ISSUE TITLE
ios compile error

### ISSUE THREAD

**Issue by HMMApps** [lohanidamodar/flutter_ui_challenges#56]
i did flutter clean , then run for ios i got the following 

Error output from Xcode build:
↳
    2020-11-22 00:22:44.799 xcodebuild[22325:4096498]  DVTProvisioningProfileManager: Failed to load profile "/Users/alkhateeb/Library/MobileDevice/Provisioning Profiles/t.plist" (Error Domain=DVTProvisioningProfileSourceErrorDomain Code=0 "No provisioning profile provider found for profile "/Users/alkhateeb/Library/MobileDevice/Provisioning Profiles/t.plist"." UserInfo={NSLocalizedDescription=No provisioning profile provider found for profile "/Users/alkhateeb/Library/MobileDevice/Provisioning Profiles/t.plist".})
    ** BUILD FAILED **

Xcode's output:
↳
    ../../.pub-cache/hosted/pub.dartlang.org/wave-0.0.8/lib/config.dart:46:13: Error: Method not found: 'throwNullError'.
                throwNullError('custom', 'colors` or `gradients');
                ^^^^^^^^^^^^^^
    ../../.pub-cache/hosted/pub.dartlang.org/wave-0.0.8/lib/config.dart:60:13: Error: Method not found: 'throwNullError'.
                throwNullError('custom', 'durations');
                ^^^^^^^^^^^^^^
    ../../.pub-cache/hosted/pub.dartlang.org/wave-0.0.8/lib/config.dart:66:13: Error: Method not found: 'throwNullError'.
                throwNullError('custom', 'heightPercentages');
                ^^^^^^^^^^^^^^

    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

**Comment by lohanidamodar** [comment]
Hi, I am aware of the error, it's caused by Wave package, which is not updated for latest flutter. I am pushing the fix soon. However if you want to work right away, remove the wave package, it's used in only one UI, remove the use as well, then it will work fine.

**Comment by HMMApps** [comment]
> Hi, I am aware of the error, it's caused by Wave package, which is not updated for latest flutter. I am pushing the fix soon. However if you want to work right away, remove the wave package, it's used in only one UI, remove the use as well, then it will work fine.

thanks dear it works with your above suggestion now .
